name: passworld
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.4
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  localstore: ^1.2.0
  flutter_secure_storage: ^5.0.2
  flutter_phoenix: ^1.0.0
  crypto: ^3.0.1
  uuid: ^3.0.5
  flutter_dotenv: ^5.0.2
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: True Lies
      fonts:
        - asset: fonts/True Lies.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-VariableFont_wght.ttf

    - family: Quicksand-semibold
      fonts:
        - asset: fonts/Quicksand-SemiBold.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
